version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dj_web_utils
      POSTGRES_DB: dj_web_utils
      POSTGRES_PASSWORD: dj_web_utils
    ports:
      # Expose some ports to local host
      - "5432:5432"
