services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dj_web_utils
      POSTGRES_DB: dj_web_utils
      POSTGRES_PASSWORD: dj_web_utils

  django_web_utils:
    image: ${DOCKER_IMG}
    hostname: djwutils
    environment:
      DJANGO_SETTINGS_MODULE: settings
      PYTHONPATH: /opt/src/tests:${PYTHONPATH}
      POSTGRES_NAME: dj_web_utils
      POSTGRES_USER: dj_web_utils
      POSTGRES_PASSWORD: dj_web_utils
      POSTGRES_HOSTNAME: db
      NEED_CLAMAV: ${NEED_CLAMAV}
    command: python3 tests/manage.py runserver 0.0.0.0:8200
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        - CLAMAV_MIRROR
        - USER_GID
        - USER_UID
    volumes:
      - type: bind
        source: ..
        target: /opt/src
    ports:
      - "8200:8200"
    depends_on:
      - db
