version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dj_web_utils
      POSTGRES_DB: dj_web_utils
      POSTGRES_PASSWORD: dj_web_utils
    ports:
      - "5432:5432"
  django:
    image: debian
    environment:
      DJANGO_SETTINGS_MODULE: settings
      PYTHONPATH: /opt/src/tests:${PYTHONPATH}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        - SKYREACH_APT_TOKEN
        - CLAMAV_MIRROR
    volumes:
      - type: bind
        source: ..
        target: /opt/src
    ports:
      - "8200:8200"
    depends_on:
      - db