version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: dj_web_utils
      POSTGRES_DB: dj_web_utils
      POSTGRES_PASSWORD: dj_web_utils
  django_web_utils:
    image: debian
    environment:
      DJANGO_SETTINGS_MODULE: settings
      PYTHONPATH: /opt/src/tests:${PYTHONPATH}
      POSTGRES_NAME: dj_web_utils
      POSTGRES_USER: dj_web_utils
      POSTGRES_PASSWORD: dj_web_utils
      POSTGRES_HOSTNAME: db
    command: python3 tests/manage.py runserver 0.0.0.0:8200
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        - CLAMAV_MIRROR
    volumes:
      - type: bind
        source: ..
        target: /opt/src
    ports:
      - "8200:8200"
    depends_on:
      - db
